import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScrollProvider from "./components/ui/SmoothScrollProvider";

const geistSans = Geist({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Desi Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <SmoothScrollProvider>
          <main >{children}</main>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
